include: ../analysis_options.yaml

# enable riverpod_lint
analyzer:
  plugins:
    - custom_lint

linter:
  rules:
    type_annotate_public_apis: false
    close_sinks: false
    avoid_print: false
    public_member_api_docs: false
    use_key_in_widget_constructors: false 
    diagnostic_describe_all_properties: false
