name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.0
  flutter_gen_runner: ^5.10.0
  flutter_svg: ^2.0.17
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.4
  mockito: ^5.4.5
  riverpod_generator: ^2.6.3
  riverpod_lint:

flutter:
  uses-material-design: true
