include: all_lint_rules.yaml
analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    included_file_warning: ignore
    invalid_annotation_target: ignore
    unused_element_parameter: false
    unrecognized_error_code: ignore

linter:
  rules:
    use_to_and_as_if_applicable: false
    avoid_classes_with_only_static_members: false
    discarded_futures: false
    combinators_ordering: false
    eol_at_end_of_file: false
    no_leading_underscores_for_local_identifiers: false
    one_member_abstracts: false
    prefer_final_parameters: false
    diagnostic_describe_all_properties: false
    always_put_control_body_on_new_line: false
    cascade_invocations: false
    prefer_double_quotes: false
    always_specify_types: false
    unnecessary_final: false
    prefer_expression_function_bodies: false
    always_put_required_named_parameters_first: false
    flutter_style_todos: false
    avoid_catches_without_on_clauses: false
    lines_longer_than_80_chars: false
    avoid_annotating_with_dynamic: false
    always_use_package_imports: false
    no_default_cases: false
