name: riverpod_view_model
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/kosukesaigusa/riverpod_view_model

environment:
  sdk: ^3.6.0

dependencies:
  riverpod: ^2.0.0

dev_dependencies:
  test: ^1.24.0
